### PR TITLE
Fixed some typos

### PR DESCRIPTION
**Pull request by dbrgn**
Additionally, a type suffix is not necessary for multiplication with a literal, the type is automatically derived.

### CODE REVIEW

**Comment by dns2utf8** [comment]
Very cool, can you rebase it?

**Comment by dbrgn** [comment]
Done. I hope the multi line string literal doesn't break anything.

**Comment by rnestler** [comment]
> Done. I hope the multi line string literal doesn't break anything.

You could have used the [`concat!`](https://doc.rust-lang.org/std/macro.concat!.html) macro if you don't like multi line string literals.

**Comment by dbrgn** [comment]
Good point, will try to remember that in the future ::)

**Pull request merged**
